/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as StatusRouteImport } from "./routes/status";
import { Route as HistoryRouteImport } from "./routes/history";
import { Route as IndexRouteImport } from "./routes/index";

const StatusRoute = StatusRouteImport.update({
  id: "/status",
  path: "/status",
  getParentRoute: () => rootRouteImport,
} as any);
const HistoryRoute = HistoryRouteImport.update({
  id: "/history",
  path: "/history",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/history": typeof HistoryRoute;
  "/status": typeof StatusRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/history": typeof HistoryRoute;
  "/status": typeof StatusRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/history": typeof HistoryRoute;
  "/status": typeof StatusRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/history" | "/status";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/history" | "/status";
  id: "__root__" | "/" | "/history" | "/status";
  fileRoutesById: FileRouteTypes["fileRoutesById"];
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  HistoryRoute: typeof HistoryRoute;
  StatusRoute: typeof StatusRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/status": {
      id: "/status";
      path: "/status";
      fullPath: "/status";
      preLoaderRoute: typeof StatusRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/history": {
      id: "/history";
      path: "/history";
      fullPath: "/history";
      preLoaderRoute: typeof HistoryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  StatusRoute: StatusRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
